version: '3.8'

volumes:
  database:

services:
  db:
    image: "mariadb:latest"
    restart: unless-stopped
    #    env_file: [ .env ]
    environment:
      MYSQL_DATABASE: alicedb
      MYSQL_USER: root
      MYSQL_PASSWORD: test123
      MYSQL_ROOT_PASSWORD: test123
    #      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
    #      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - "3306:3306"
    networks:
      - my-app
    volumes:
      - database:/var/lib/mysql
  backend:
    depends_on: [ db ]
    build: backend
    restart: unless-stopped
    env_file: [ .env ]
    environment:
      SPRING_APPLICATION_JSON: '{
           "spring.datasource.url"  : "jdbc:mariadb://db:3306/alicedb?useSSL=false",
           "spring.datasource.username" : "root",
           "spring.datasource.password" : "test123",
           "spring.datasource.driver-class-name" : "org.mariadb.jdbc.Driver",
           "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MariaDB103Dialect",
           "spring.jpa.hibernate.ddl-auto" : "update",
           "server.error.include-message" : "always"
         }'
    ports:
      - "8080:8080"
      - "5005:5005"
    networks:
      - my-app
    stdin_open: true
    tty: true
  frontend:
    depends_on: [ backend ]
    build: frontend
    restart: unless-stopped
    env_file: [ .env ]
    ports:
      - "80:80"
    networks:
      - my-app
networks:
  my-app:
   driver: bridge
